localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=user_crud

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=user_crud