localdb:
  image: postgres:11.2
  ports:
    - '5442:5442'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=enquete

testdb:
  image: postgres:11.2
  ports:
    - '5443:5442'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=enquete
